# Generated by Django 4.0.3 on 2023-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listing_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
